language: go
go:
    - 1.6
    - 1.7
    - tip
dist: trusty
sudo: required
before_install:
    - sudo apt-get -qq update
    - sudo apt-get -qq install btrfs-tools libdevmapper-dev libgpgme11-dev
script:
    - make
